package testers;

import algorithms.FIFOAlgoImpl;
import algorithms.LRUAlgoImpl;
import algorithms.MFUAlgoImpl;
//import algorithms.MFUAlgoImpl;

public class AlgorithmTest {

	// compare results against: http://www.scribd.com/doc/73808713/Simulation-FIFO-LFU-and-MFU-Page-Replacement-Algorithms-VB-by-Shaify-Mehta
	
	public static void main(String[] args) {
		FIFOAlgoImpl<String> fifoAlgo = new FIFOAlgoImpl<String>(3);
		System.out.println("=================FIFO==================");
		System.out.println("7 0 1 2 0 3 0 4 2 3 0 3 2 1 2 0 1 7 0 1");
		System.out.println("=================FIFO==================");
		fifoAlgo.add("7");
		fifoAlgo.print();
		fifoAlgo.add("0");
		fifoAlgo.print();
		fifoAlgo.add("1");
		fifoAlgo.print();
		fifoAlgo.add("2");
		fifoAlgo.print();
		fifoAlgo.add("0");
		fifoAlgo.print();
		fifoAlgo.add("3");
		fifoAlgo.print();
		fifoAlgo.add("0");
		fifoAlgo.print();
		fifoAlgo.add("4");
		fifoAlgo.print();
		fifoAlgo.add("2");
		fifoAlgo.print();
		fifoAlgo.add("3");
		fifoAlgo.print();
		fifoAlgo.add("0");
		fifoAlgo.print();
		fifoAlgo.add("3");
		fifoAlgo.print();
		fifoAlgo.add("2");
		fifoAlgo.print();
		fifoAlgo.add("1");
		fifoAlgo.print();
		fifoAlgo.add("2");
		fifoAlgo.print();
		fifoAlgo.add("0");
		fifoAlgo.print();
		fifoAlgo.add("1");
		fifoAlgo.print();
		fifoAlgo.add("7");
		fifoAlgo.print();
		fifoAlgo.add("0");
		fifoAlgo.print();
		fifoAlgo.add("1");
		fifoAlgo.print();
		
		
		LRUAlgoImpl<String> lruAlgo = new LRUAlgoImpl<String>(3);
		System.out.println("=================LRU===================");
		System.out.println("7 0 1 2 0 3 0 4 2 3 0 3 2 1 2 0 1 7 0 1");
		System.out.println("=================LRU===================");
		lruAlgo.add("7");
		lruAlgo.print();
		lruAlgo.add("0");
		lruAlgo.print();
		lruAlgo.add("1");
		lruAlgo.print();
		lruAlgo.add("2");
		lruAlgo.print();
		lruAlgo.add("0");
		lruAlgo.print();
		lruAlgo.add("3");
		lruAlgo.print();
		lruAlgo.add("0");
		lruAlgo.print();
		lruAlgo.add("4");
		lruAlgo.print();
		lruAlgo.add("2");
		lruAlgo.print();
		lruAlgo.add("3");
		lruAlgo.print();
		lruAlgo.add("0");
		lruAlgo.print();
		lruAlgo.add("3");
		lruAlgo.print();
		lruAlgo.add("2");
		lruAlgo.print();
		lruAlgo.add("1");
		lruAlgo.print();
		lruAlgo.add("2");
		lruAlgo.print();
		lruAlgo.add("0");
		lruAlgo.print();
		lruAlgo.add("1");
		lruAlgo.print();
		lruAlgo.add("7");
		lruAlgo.print();
		lruAlgo.add("0");
		lruAlgo.print();
		lruAlgo.add("1");
		lruAlgo.print();
		
		MFUAlgoImpl<String> mfuAlgo = new MFUAlgoImpl<String>(3);
		System.out.println("=================MFU===================");
		System.out.println("7 0 1 2 0 3 0 4 2 3 0 3 2 1 2 0 1 7 0 1");
		System.out.println("=================MFU===================");
		mfuAlgo.add("7");
		mfuAlgo.print();
		mfuAlgo.add("0");
		mfuAlgo.print();
		mfuAlgo.add("1");
		mfuAlgo.print();
		mfuAlgo.add("2");
		mfuAlgo.print();
		mfuAlgo.add("0");
		mfuAlgo.print();
		mfuAlgo.add("3");
		mfuAlgo.print();
		mfuAlgo.add("0");
		mfuAlgo.print();
		mfuAlgo.add("4");
		mfuAlgo.print();
		mfuAlgo.add("2");
		mfuAlgo.print();
		mfuAlgo.add("3");
		mfuAlgo.print();
		mfuAlgo.add("0");
		mfuAlgo.print();
		mfuAlgo.add("3");
		mfuAlgo.print();
		mfuAlgo.add("2");
		mfuAlgo.print();
		mfuAlgo.add("1");
		mfuAlgo.print();
		mfuAlgo.add("2");
		mfuAlgo.print();
		mfuAlgo.add("0");
		mfuAlgo.print();
		mfuAlgo.add("1");
		mfuAlgo.print();
		mfuAlgo.add("7");
		mfuAlgo.print();
		mfuAlgo.add("0");
		mfuAlgo.print();
		mfuAlgo.add("1");
		mfuAlgo.print();
	
	}
}
